services:
  mysql-master:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=t123
      - MARIADB_USER=ds_user
      - MARIADB_PASSWORD=t123
      - MARIADB_DATABASE=dsdb
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-uroot", "-pt123"]
      interval: 5s
      retries: 5

  mysql-replica:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mysql-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_USER=root
      - MARIADB_MASTER_ROOT_PASSWORD=t123
      - MARIADB_ROOT_PASSWORD=t123
      - MARIADB_USER=ds_user
      - MARIADB_PASSWORD=t123
      - MARIADB_DATABASE=dsdb
    depends_on:
      mysql-master:
        condition: service_healthy

  haproxy:
    image: haproxy:latest
    ports:
      - "3307:3307"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - mysql-master
      - mysql-replica
